version: "3.9"
services: 
  site:
    container_name: siteapp
    image: siteapp
    build:
      context: https://github.com/CloudNStoyan/basicwebsite.git
    ports:
      - "80:80"
    volumes:
      - /test:/app/wwwroot/test
  db:
    container_name: postgresdb
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg/infile:/infile
      - pg_data:/var/lib/postgresql/data/