version: "3.9"
services: 
  site:
    container_name: siteapp
    image: siteapp
    build:
      context: https://github.com/CloudNStoyan/basicwebsite.git
    ports:
      - "80:80"
    volumes:
      - /test:/app/wwwroot/test